config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/edit_services', to: 'users#edit_services', as: :edit_services
  get 'users/:id/show_services', to: 'users#show_services', as: :show_services
  get 'services/:id/book', to: 'services#book', as: :book_service
  get 'search', to: 'application#search', as: :search
  post 'services/:id/book_payment', to: 'services#book_payment', as: :book_payment
  post 'services/:id/booking_completed', to: 'services#booking_completed', as: :booking_completed
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    resource :calendar
  end
  resources :profiles, except: [:show, :index]
  resources :services, except: [:index]
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  include ActiveModel::Validations
  validates_with ServiceValidator
  belongs_to :user

  FIELDS = %w(
    name
    duration
    description
  )
  FIELDS.each do |field|
    define_method(field) do
      servicedata[field.to_s]
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  layout 'user' # TODO change to services new own layout

  def initialize
    super
    @calendars_service = CalendarsService.new
    @services_service = ServicesService.new
  end

  # GET /services/1
  # GET /services/1.json
  def show
    set_service_and_provider
    init_presenter
    render 'show', locals: { view_data: @services_presenter.show_data(@service.servicedata) }
  end

  # GET /services/new
  def new
    require_profile?(current_user) or return
    @service = @services_service.new_service(current_user.id)
    init_presenter
  end

  # GET /services/1/edit
  def edit
    set_service_and_provider
    require_permission? or return
    init_presenter
  end

  # POST /services
  # POST /services.json
  def create
    @service = @services_service.new_service(current_user.id, service_params)
    @service.servicedata = params[:service][:servicedata]
    @services_service.update_text_search_column(current_user, @service)
    respond_to do |format|
      if @service.save
        format.html { redirect_to show_services_path(current_user.id),
                                  notice: 'Service was successfully created.' }
        format.json { render :show,
                             locals: { view_data: @services_presenter.show_data(@service.servicedata) },
                             status: :created,
                             location: @service }
      else
        init_presenter
        format.html { render :new,
                             locals: { view_data: @services_presenter.form_data(@service.servicedata) } }
        format.json { render json: @service.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    set_service_and_provider
    require_permission? or return
    @service.servicedata = params[:service][:servicedata]
    @services_service.update_text_search_column(current_user, @service)
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    set_service_and_provider
    require_permission? or return
    @service.destroy
    respond_to do |format|
      format.html { redirect_to edit_services_path(@provider), notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book
    require_profile?(current_user) or return
    set_service_and_provider
    prevent_own_booking? or return
    my_calendar_data = @calendars_service.get_data_for_timeline(current_user, false)
    provider_calendar_data = @calendars_service.get_data_for_timeline(@provider, true)
    free_intervals = @calendars_service.get_free_intervals_for(
      my_calendar_data,
      provider_calendar_data,
      @service
    )
    init_presenter
    init_calendars_presenter
    render 'book', locals: {
      view_data: @services_presenter.book_data(
        current_user,
        my_calendar_data,
        @provider,
        provider_calendar_data,
        free_intervals
      )
    }
  end

  def book_payment
    require_profile?(current_user) or return
    set_service_and_provider
    prevent_own_booking? or return
    day, hours, minutes = Date.today, params[:bookAtHours], params[:bookAtMinutes]
    # TODO replace Date.today with date from request (date picker)
    if @services_service.booking_is_available?(
      current_user,
      @service,
      @services_service.format_booking_date(day, hours, minutes)
    )
      init_presenter
      render 'book_payment', locals: {
        view_data: @services_presenter.book_payment_data(day, hours, minutes)
      }
    else
      redirect_to service_path(@service),
                  notice: 'Something went wrong and booking is unavailable.'
    end
  end

  def booking_completed
    require_profile?(current_user) or return
    set_service_and_provider
    prevent_own_booking? or return
    if @services_service.booking_performed?(
      current_user,
      @service,
      @services_service.format_booking_date(
        Date.parse(params[:day]),
        params[:hours],
        params[:minutes]
      )
    )
      message = 'You\'ve successfully booked the service.'
    else
      message = 'Something went wrong and booking was cancelled.'
    end
    init_presenter
    render 'booking_completed', locals: {
      view_data: @services_presenter.booking_completed_data(message)
    }
  end

  private

  def require_permission?
    if @provider.id != current_user.id
      redirect_to user_path(current_user.id),
                  notice: 'Editing or deleting of other\'s service is forbidden.'
      return false
    end
    true
  end

  def prevent_own_booking?
    if @provider.id == current_user.id
      redirect_to user_path(current_user.id),
                  notice: 'You cannot book your own services!'
      return false
    end
    true
  end

  def init_presenter
    @services_presenter = ServicesPresenter.new
  end

  def init_calendars_presenter
    @calendars_presenter = CalendarsPresenter.new(current_user.id)
  end

  def set_service_and_provider
    @service = Service.find(params[:id])
    @provider = User.preload(:profile).find(@service.user_id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:servicedata)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <label for="service[servicedata][name]">Service name</label>
  <% if service.errors[:name].any? %>
    <span class="label label-warning"
          data-toggle="popover"
          data-trigger="hover"
          data-content="<%= service.errors[:name][0] %>"
          data-original-title="Warning">!
    </span>
  <% end %>
  <input type="text"
         id="service[servicedata][name]"
         name="service[servicedata][name]"
         class="form-control"
         value="<%= view_data[:name] %>" />
  <br/>
  <label for="service[servicedata][duration]">Average duration</label>
  <input type="number"
         id="rangeDoubler"
         name="rangeDoubler"
         min="1"
         max="120"
         value="<%= view_data[:duration] %>" />
  minutes
  <input type="range"
         id="service[servicedata][duration]"
         name="service[servicedata][duration]"
         min="1"
         max="120"
         class="form-control"
         value="<%= view_data[:duration] %>" />
  <br/>
  <label for="setRestTimeDefault">Use default rest time (from calendar)</label>
  <input id="setRestTimeDefault"
         type="checkbox"
         onchange = "disable_rest_time_inputs(this)" />
  <br/>
  <label for ="service[servicedata][rest_time]">Rest time</label>
  <input type="number"
         id="restDoubler"
         name="restDoubler"
         min="1"
         max="60"
         value="<%= view_data[:rest_time] %>" />
  minutes
  <input type="range"
         id="service[servicedata][rest_time]"
         name="service[servicedata][rest_time]"
         min="1"
         max="60"
         class="form-control"
         value="<%= view_data[:rest_time] %>" />
  <br/>
  <label for="service[servicedata][description]">You may add some description here</label>
  <span class="label label-info"
        data-toggle="popover"
        data-trigger="hover"
        data-content="You don't have to write out your personal info (phone, address, etc.) here;
        it is seen from your profile page."
        data-original-title="Info">!
  </span>
  <textarea maxlength="500"
            id="service[servicedata][description]"
            name="service[servicedata][description]"
            rows="6"
            class="form-control"
            style="resize: none"><%= view_data[:description] %>
  </textarea>
  <br/>
  <%= f.submit %>
<% end %>

app/views/services/book.html.erb
<h2>My calendar:</h2>
<div class="calendars-holder">
  <%= render 'calendars/calendar_timeline',
             view_data: @calendars_presenter.calendar_timeline_data(
                 view_data[:my_preferences],
                 view_data[:me]
             ),
             timeline_data: view_data[:my_calendar_data] %>
<h2><%= view_data[:provider_name] %>'s calendar:</h2>
  <%= render 'calendars/calendar_timeline',
             view_data: @calendars_presenter.calendar_timeline_data(
                 view_data[:provider_preferences],
                 view_data[:provider]
             ),
             timeline_data: view_data[:provider_calendar_data] %>
  <% if view_data[:booking_is_available] %>
    <%= render 'calendars/calendar_runner',
               duration: @service.servicedata['duration'],
               free: view_data[:free_intervals] %>
  <% end %>
</div>
<% if view_data[:booking_is_available] %>
  <%= render 'calendars/booking_form', at_time: view_data[:free_intervals].start %>
<% end %>
<%= render 'calendars/calendar_legend' %>
<br/>
<%= link_to 'Back to service', service_path(@service) %>

app/views/services/book_payment.html.erb
<h2>Service booking</h2>
<br/>
<br/>
You are going to book
<b><%= @service[:servicedata]['name'] %></b>
at
<b><%= view_data[:day] %></b>,
<b><%= view_data[:hours] %>:<%= view_data[:minutes] %></b>.
<br/>
<%= form_tag booking_completed_path, authenticity_token: form_authenticity_token do %>
  <input type="hidden" name="day" value="<%= view_data[:day] %>" />
  <input type="hidden" name="hours" value="<%= view_data[:hours] %>" />
  <input type="hidden" name="minutes" value="<%= view_data[:minutes] %>" />
  <input type="submit" value="Yes, book" />
<% end %>
<br/>
<%= link_to 'No, I\'ve changed my mind', service_path(@service) %>

app/views/services/booking_completed.html.erb
<h3>Booked successfully!</h3>
<%= link_to 'Back to service', book_service_path(@service) %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form',
           service: @service,
           view_data: @services_presenter.form_data(@service.servicedata) %>
<br/>

<% if service_url(@service) != _back_url %>
  <%= link_to 'Show', @service %>
  <br/>
  <br/>
<% end %>
<%= link_to 'Back', :back %>

app/views/services/index.html.erb
<div class="with-user-links">
  <p id="notice"><%= notice %></p>

  <h1>Services</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Servicedata</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.user_id %></td>
          <td><%= service.servicedata %></td>
          <td><%= link_to 'Show', service %></td>
          <td><%= link_to 'Edit', edit_service_path(service) %></td>
          <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <%= link_to 'New Service', new_service_path %>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form',
           service: @service,
           view_data: @services_presenter.form_data(@service.servicedata) %>

<br/>

app/views/services/show.html.erb
<div class="row">
  <div class="col-sm-10">
    <p id="notice"><%= notice %></p>

    <h2>Service <b><%= view_data[:name] %></b></h2>
    <br/>

    <b>Provided by </b><%= @provider.profile.personaldata['name'] %>
    <br/>
    <br/>
    <b>Average duration </b> <%= view_data[:duration] %> minutes
    <br/>
    <br/>
    <b>Description</b>
    <br/>
    <%= view_data[:description] %>
  </div>

  <div class="col-sm-2 edit-buttons">
    <% if @provider.id == current_user.id %>
      <%= link_to 'Edit service', edit_service_path(@service)%>
      <%= link_to 'Delete service',
          @service,
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
    <% else %>
      <%= link_to 'All this user\'s services', show_services_path(@provider) %>
      <%= link_to 'Book this service', book_service_path(@service) %>
    <% end %>
  </div>
</div>