config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/edit_services', to: 'users#edit_services', as: :edit_services
  get 'users/:id/show_services', to: 'users#show_services', as: :show_services
  get 'services/:id/book', to: 'services#book', as: :book_service
  get 'search', to: 'application#search', as: :search
  post 'services/:id/book_payment', to: 'services#book_payment', as: :book_payment
  post 'services/:id/booking_completed', to: 'services#booking_completed', as: :booking_completed
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    resource :calendar
  end
  resources :profiles, except: [:show, :index]
  resources :services, except: [:index]
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :create_calendar
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
  has_one :profile
  has_one :calendar
  has_many :services

  def create_calendar
    Calendar.create user_id: self.id, preferences:
      '{"serving_start": "540", "break_start": "720", "break_finish": "780", "serving_finish": "1080"}'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user' # why isn't it set automatically?

  def initialize
    super
    @users_service = UsersService.new
  end

  def show
    user = @users_service.find_user(params)
    init_presenter
    render 'show', locals: { view_data: @users_presenter.show_data(user, current_user) }
  end

  def edit_services
    user = @users_service.find_user(params)
    require_permission?(user) or return
    require_profile?(user) or return
    @services = @users_service.find_user_services(user)
  end

  def show_services
    @user = @users_service.find_user(params)
    require_profile?(@user) or return
    prevent_own_ordering?(@user) or return
    @services = @users_service.find_user_services(@user)
  end

  private

  def require_permission?(user)
    if user.id != current_user.id
      redirect_back fallback_location: user_path(current_user),
                    notice: 'Editing of another user is forbidden.'
      return false
    end
    true
  end

  def prevent_own_ordering?(user)
    if user.id == current_user.id
      redirect_to edit_services_path(user)
      return false
    end
    true
  end

  def init_presenter
    @users_presenter = UsersPresenter.new
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def format_name(service)
    service.servicedata && service.servicedata['name'] || ''
  end

  def format_duration(service)
    (service.servicedata && service.servicedata['duration'] || '') + ' minutes'
  end

end

app/views/users/edit_services.html.erb
<div class="row with-user-links">
  <div class="col-sm-10">
    <% if @services.empty? %>
      No services have been added yet.
      <br/>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Service name</th>
            <th>Service duration</th>
          </tr>
        </thead>
        <tbody>
          <% @services.each do |service| %>
            <tr>
              <td><%= format_name(service) %></td>
              <td><%= format_duration(service) %></td>
              <td><%= link_to 'View', service_path(service) %></td>
              <td><%= link_to 'Edit', edit_service_path(service) %></td>
              <td><%= link_to 'Delete',
                              service_path(service),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class="col-sm-2 edit-buttons">
    <%= link_to 'New service', new_service_path %>
  </div>
</div>

app/views/users/show.html.erb
<% if view_data[:user].errors.any? %>
  <div id="error_explanation" class="notshown">
    <ul>
      <% view_data[:user].errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row row-eq-height with-user-links">
  <div class="col-sm-3">
    <img src="<%= asset_path('Profile_photo_blank.png') %>" class="user-photo">
  </div>

  <div class="col-sm-6">
    <div class="row">
      <div class="col-sm-2"><b>
        Name
      </b></div>
      <div class="col-sm-3">
        <%= view_data[:json]['name'] %>
      </div>
      <div class="col-sm-2 col-sm-push-1"><b>
        Country
      </b></div>
      <div class="col-sm-3 col-sm-push-1">
        <%= view_data[:json]['country'] %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2"><b>
        Email
      </b></div>
      <div class="col-sm-3">
        <%= view_data[:user].email %>
      </div>
      <div class="col-sm-2 col-sm-push-1"><b>
        City
      </b></div>
      <div class="col-sm-3 col-sm-push-1">
        <%= view_data[:json]['city'] %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2"><b>
        Phone
      </b></div>
      <div class="col-sm-3">
        <%= view_data[:json]['phone'] %>
      </div>
      <div class="col-sm-2 col-sm-push-1"><b>
        Address
      </b></div>
      <div class="col-sm-3 col-sm-push-1">
        <%= view_data[:json]['address'] %>
      </div>
    </div>
  </div>

  <div class="col-sm-2 col-sm-push-1 edit-buttons">
    <% if view_data[:user_is_owner] %>
      <% if view_data[:profile_is_present] %>
        <%= link_to 'Edit my profile', edit_profile_path(view_data[:profile]) %>
      <% else %>
        <%= link_to 'Create profile', new_profile_path %>
      <% end %>
    <% else %>
      <% if view_data[:profile_is_present] %>
        <%= link_to 'View services', show_services_path(view_data[:user]) %>
        <%= link_to view_data[:profile].personaldata['name'] + '\'s calendar',
                    user_calendar_path(view_data[:user]) %>
      <% end %>
    <% end %>
  </div>

</div>

<br/>

<div class="row">
  <div class="col-sm-12">
    <%= commontator_thread(view_data[:user]) %>
  </div>
</div>

app/views/users/show_services.html.erb
<div class="row with-user-links">
  <div class="col-sm-10">
    <% if @services.empty? %>
      No services of this user are available.
      <br/>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Service name</th>
            <th>Service duration</th>
          </tr>
        </thead>
        <tbody>
          <% @services.each do |service| %>
            <tr>
              <td><%= format_name(service) %></td>
              <td><%= format_duration(service) %></td>
              <td><%= link_to 'View', service_path(service) %></td>
              <td><%= link_to 'Book', book_service_path(service) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class="col-sm-2 edit-buttons">
    <%= link_to 'Back to ' + @user.profile.personaldata['name'] + '\'s page',
                user_path(@user) %>
  </div>
</div>