config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/edit_services', to: 'users#edit_services', as: :edit_services
  get 'users/:id/show_services', to: 'users#show_services', as: :show_services
  get 'services/:id/book', to: 'services#book', as: :book_service
  get 'search', to: 'application#search', as: :search
  post 'services/:id/book_payment', to: 'services#book_payment', as: :book_payment
  post 'services/:id/booking_completed', to: 'services#booking_completed', as: :booking_completed
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    resource :calendar
  end
  resources :profiles, except: [:show, :index]
  resources :services, except: [:index]
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  layout 'user'

  def show
    set_services
    user = @users_service.find_user(params)
    require_profile?(user) or return
    @timeline_data = @calendars_service.get_data_for_timeline(user, false)
    init_presenter
    render 'show', locals: { view_data: @calendars_presenter.show_data(user) }
  end

  def edit
    set_services
    user = @users_service.find_user(params)
    require_permission?(user) or return
    require_profile?(user) or return
    init_presenter
    render 'edit', locals: { view_data: @calendars_presenter.edit_data(user.calendar) }
  end

  def update
    set_services
    user = @users_service.find_user(params)
    require_permission?(user) or return
    require_profile?(user) or return
    json = params[:calendar][:preferences]
    data_is_correct_for?(json) or return
    @calendars_service.update_preferences_border_values(json)
    user.calendar.preferences = json
    if user.calendar.update(calendar_params)
      redirect_to user_calendar_path
    else
      init_presenter
      render 'edit', locals: { view_data: @calendars_presenter.edit_data(user.calendar) }
    end
  end

  private

  def require_permission?(user)
    if user.id != current_user.id
      redirect_to user_path(user),
                  notice: 'Editing or deleting of other\'s calendar is forbidden.'
      return false
    end
    true
  end

  def data_is_correct_for?(json)
    unless @calendars_service.check_for_correct_calendar_data?(json)
      redirect_to user_path(current_user.id),
                  notice: 'Parameters for calendar seem to be incorrect.'
      return false
    end
    true
  end

  def set_services
    @calendars_service = CalendarsService.new
    @users_service = UsersService.new
  end

  def init_presenter
    @calendars_presenter = CalendarsPresenter.new(current_user.id)
  end

  def calendar_params
    params.require(:calendar).permit(:preferences)
  end

end

app/helpers/calendars_helper.rb
module CalendarsHelper

  # TIMELINE_PERCENT == 1% of day in minutes (useful for rendering calendars)
  TIMELINE_PERCENT = CalendarsService::MINUTES_IN_DAY / 100.0

  def width(minute_block)
    minute_block.to_i / TIMELINE_PERCENT
  end

  def format_width(value)
    "width: #{width(value)}%; "
  end

  def format_left(value)
    "left: #{width(value)}%; "
  end

  def format_width_and_left(width_value, left_value)
    format_width(width_value) + format_left(left_value)
  end

  def format_complement_width(minute_block)
    format_width(CalendarsService::MINUTES_IN_DAY - minute_block.to_i)
  end

  def hours(total_minutes)
    total_minutes / 60
  end

  def minutes(total_minutes)
    total_minutes % 60
  end

  def format_hours_and_minutes(total_minutes)
    "#{format_time_value(hours(total_minutes))}:#{format_time_value(minutes(total_minutes))}"
  end

  def format_time_value(value)
    value.to_s.rjust(2, '0')
  end

end

app/views/calendars/_booking_form.html.erb
<br/>
<span>Book this service at:</span>
<%= form_tag book_payment_path, authenticity_token: form_authenticity_token do %>
  <input type="number"
         id="bookAtHours"
         name="bookAtHours"
         min="0"
         max="23"
         step="1"
         value="<%= hours(at_time) %>" /> hours
  <input type="number"
         id="bookAtMinutes"
         name="bookAtMinutes"
         min="0"
         max="59"
         step="1"
         value="<%= minutes(at_time) %>" /> minutes
  <input type="submit" value="Book" />
<% end %>

app/views/calendars/_calendar_item.html.erb
<div class="timeline <%= view_data[:class_name] %>" style=
  "<%= format_width_and_left(view_data[:duration], view_data[:minutes]) %>"
  data-toggle="popover"
  data-trigger="hover"
  data-placement="top"
  data-content="<%= view_data[:description] %>"
  data-original-title="<%= view_data[:title] %>">
</div>
<% if view_data[:should_render_rest] %>
  <div class="timeline tl-rest-time" style=
    "<%= format_width_and_left(view_data[:rest_time], view_data[:rest_offset]) %>"
    data-toggle="popover"
    data-trigger="hover"
    data-placement="top"
    data-content="rest after service for <%= view_data[:rest_time] %> minutes."
    data-original-title="Rest time">
  </div>
<% end %>

app/views/calendars/_calendar_labels.html.erb
<% view_data[:all_time_marks].each do |mark| %>
  <div class="interval-time-mark" style="<%= format_left(mark) %>">
    <b>
      <%= format_hours_and_minutes(mark) %>
    </b>
  </div>
<% end %>

app/views/calendars/_calendar_legend.html.erb
<br/>
<button class="btn btn-info" data-toggle="collapse" data-target="#demo">Legend</button>
<br/>
<br/>
<div id="demo" class="collapse">
  <div><div class="legend-item tl-my-order"></div><div>My orders</div></div>
  <div><div class="legend-item tl-ordered-at-me"></div><div>Ordered at me</div></div>
  <div><div class="legend-item tl-sided-order"></div><div>Other orders</div></div>
  <div><div class="legend-item tl-rest-time"></div><div>Rest time after services</div></div>
  <div><div class="legend-item tl-free"></div><div>Free time</div></div>
  <div><div class="legend-item tl-out-of-work"></div><div>
    Time out of work (unavailable for customers but can book services)</div></div>
</div>

app/views/calendars/_calendar_runner.html.erb
<div id="calendar-runner"
     class="available"
     style="<%= format_width_and_left(duration, free.start) %>"
     data-attributes="<%= free %>">
</div>

app/views/calendars/_calendar_timeline.html.erb
<div class="timeline tl-free">
  <%= render 'calendars/calendar_labels',
             view_data: timeline_data %>
  <div class="timeline tl-out-of-work" style="<%= format_width(view_data[:serving_start]) %>"></div>
  <div class="timeline tl-out-of-work" style="
    <%= format_complement_width(view_data[:serving_finish]) %>
    <%= format_left(view_data[:serving_finish]) %>">
  </div>
  <% if view_data[:break_start] %>
    <div class="timeline tl-out-of-work"
         style="<%= format_width_and_left(view_data[:break_length], view_data[:break_start]) %>">
    </div>
  <% end %>
  <% timeline_data[:my_orders].each do |order| %>
    <%= render 'calendars/calendar_item',
               view_data: @calendars_presenter.calendar_item_data(order, view_data[:id]) %>
  <% end %>
  <% timeline_data[:ordered_at_me].each do |order| %>
    <%= render 'calendars/calendar_item',
               view_data: @calendars_presenter.calendar_item_data(order, view_data[:id]) %>
  <% end %>
</div>

app/views/calendars/edit.html.erb
<%= form_for (view_data[:calendar]), url: {action: 'update'} do |f| %>
  <label for="calendar[preferences][serving_start]">Time when you start working:</label>
  <input type="number"
         id="startDoublerHours"
         name="startDoublerHours"
         min="0"
         max="23"
         step="1"
         value="<%= hours(view_data[:serving_start]) %>" /> hours
  <input type="number"
         id="startDoublerMinutes"
         name="startDoublerMinutes"
         min="0"
         max="59"
         step="1"
         value="<%= minutes(view_data[:serving_start]) %>" /> minutes
  <input type="range"
         id="calendar[preferences][serving_start]"
         name="calendar[preferences][serving_start]"
         min="0"
         max="<%= @calendars_presenter.max_minute %>"
         step="1"
         value="<%= view_data[:serving_start] %>" />

  <label for="calendar[preferences][serving_finish]">Time when you usually finish working:</label>
  <input type="number"
         id="finishDoublerHours"
         name="finishDoublerHours"
         min="0"
         max="23"
         step="1"
         value="<%= hours(view_data[:serving_finish]) %>" /> hours
  <input type="number"
         id="finishDoublerMinutes"
         name="finishDoublerMinutes"
         min="0"
         max="59"
         step="1"
         value="<%= minutes(view_data[:serving_finish]) %>" /> minutes
  <input type="range"
         id="calendar[preferences][serving_finish]"
         name="calendar[preferences][serving_finish]"
         min="0"
         max="<%= @calendars_presenter.max_minute %>"
         step="1"
         value="<%= view_data[:serving_finish] %>" />

  <label for="calendar[preferences][break_start]">Time to have a break:</label>
  <input type="number"
         id="breakStartDoublerHours"
         name="breakStartDoublerHours"
         min="0"
         max="23"
         step="1"
         value="<%= hours(view_data[:break_start]) %>" /> hours
  <input type="number"
         id="breakStartDoublerMinutes"
         name="breakStartDoublerMinutes"
         min="0"
         max="59"
         step="1"
         value="<%= minutes(view_data[:break_start]) %>" /> minutes
  <input type="range"
         id="calendar[preferences][break_start]"
         name="calendar[preferences][break_start]"
         min="0"
         max="<%= @calendars_presenter.max_minute %>"
         step="1"
         value="<%= view_data[:break_start] %>" />

  <label for="calendar[preferences][break_finish]">Time to go back to work:</label>
  <input type="number"
         id="breakFinishDoublerHours"
         name="breakFinishDoublerHours"
         min="0"
         max="23"
         step="1"
         value="<%= hours(view_data[:break_finish]) %>" /> hours
  <input type="number"
         id="breakFinishDoublerMinutes"
         name="breakFinishDoublerMinutes"
         min="0"
         max="59"
         step="1"
         value="<%= minutes(view_data[:break_finish]) %>" /> minutes
  <input type="range"
         id="calendar[preferences][break_finish]"
         name="calendar[preferences][break_finish]"
         min="0"
         max="<%= @calendars_presenter.max_minute %>"
         step="1"
         value="<%= view_data[:break_finish] %>" />

  <label for="calendar[preferences][rest_time]">Average time to take rest between services:</label>
  <span class="label label-info" data-toggle="popover" data-trigger="hover"
        data-content="During that time after service execution, you'll be
  unavailable for other customers. You can always set rest time for
  every certain service. This value is set by default." data-original-title="Info">!</span>
  <input type="number"
         id="restTimeDoubler"
         name="restTimeDoubler"
         min="0"
         max="60"
         value="<%= view_data[:rest_time] %>" />
  minutes
  <input type="range"
         id="calendar[preferences][rest_time]"
         name="calendar[preferences][rest_time]"
         min="0"
         max="60"
         class="form-control"
         value="<%= view_data[:rest_time] %>" />

  <br/>
  <%= f.submit 'Update' %>
<% end %>
<br/>

app/views/calendars/show.html.erb
<div class="row with-user-links">
  <div class="col-sm-9">
    <h2><%= view_data[:calendar_title_text] %></h2>
    Select date:
    <input type="text"
           data-provide='datepicker-inline'
           data-date-max-view-mode="1"
           data-date-today-btn="linked"
           data-date-today-highlight="true"
    />
    <br/>
    <br/>
    <%= render 'calendars/calendar_timeline',
               view_data: @calendars_presenter.calendar_timeline_data(view_data[:timeline_data], view_data[:id]),
               timeline_data: @timeline_data %>
    <%= render 'calendars/calendar_legend' %>
  </div>
  <div class="col-sm-2 col-sm-push-1 edit-buttons">
    <% if view_data[:is_mine] %>
      <%= link_to 'Calendar preferences', edit_user_calendar_path %>
    <% else %>
      <%= link_to 'Back', :back %>
    <% end %>
  </div>
</div>