config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/edit_services', to: 'users#edit_services', as: :edit_services
  get 'users/:id/show_services', to: 'users#show_services', as: :show_services
  get 'services/:id/book', to: 'services#book', as: :book_service
  get 'search', to: 'application#search', as: :search
  post 'services/:id/book_payment', to: 'services#book_payment', as: :book_payment
  post 'services/:id/booking_completed', to: 'services#booking_completed', as: :booking_completed
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
    resource :calendar
  end
  resources :profiles, except: [:show, :index]
  resources :services, except: [:index]
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div style="width: 100%; height: 61px">&nbsp;</div>
  <p class="text-muted text-right">2016 Burning Buttons</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= welcome_index_url %>"><b>B</b>Booking system</a>
      <% if current_user.present? %>
        <div class="my-menu-holder">
          <button class="btn btn-default my-menu-button dropdown-toggle"
                  type="button"
                  data-toggle="dropdown"><%= fa_icon 'home' %>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Home page', user_path(current_user) %></li>
            <li><%= link_to 'My services', edit_services_path(current_user) %></li>
            <li><%= link_to 'My calendar', user_calendar_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <form id="global_search_form" action="<%= search_path %>" method="get">
          <input type="text" id="q" name="q" class="form-control" placeholder="Search..." />
          <input type="submit" class="btn btn-info" value="Go" />
        </form>
      <% end %>
    </div>
  </div>
</nav>
<div style="width: 100%; height: 60px;">&nbsp;</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbooking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container wrapper">
      <div class="row">
        <div class="col-sm-12">
          <!-- Devise gem settings -->
          <!--<p class="notice text-info notshown"><= notice %></p>-->
          <!-- TODO add some alert styles & make 'notice' notifications disappearing -->
          <p class="alert text-danger text-center notshown"><%= alert %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4 col-sm-push-4">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Landing page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-full-width">
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/search.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Bbooking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container wrapper">
      <div class="row with-user-links">
        <div class="col-sm-12">
          <h2>Search results:</h2>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your homepage</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container wrapper">
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>